---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: nomis-api-access.service.justice.gov.uk
  namespace: nomis-api-access-production
spec:
  secretName: nomis-api-access-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: 'nomis-api-access.service.justice.gov.uk'
  acme:
    config:
    - domains:
      - 'nomis-api-access.service.justice.gov.uk'
      dns01:
        provider: route53-cloud-platform
