# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/digital-prison-services/nomis-api-access-production
  tag: v1.0
  pullPolicy: Always

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/whitelist-source-range: "217.33.148.210/32,81.134.202.29/32"
  hosts:
    - host: nomis-api-access.service.justice.gov.uk
      cert_secret: nomis-api-access-cert 
  path: /

deploy:
  AUTH_ENABLED: true
  NOTIFY_ENABLED: true
  MOJSSO_URL: https://signon.service.justice.gov.uk
  RECAPTCHA_ENABLED: true
