apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nomis-api-access.fullname" . }}
type: Opaque
data:
  API_AUTH: {{ .Values.secrets.API_AUTH | b64enc | quote }} 
  GOVUK_NOTIFY_API_KEY: {{ .Values.secrets.GOVUK_NOTIFY_API_KEY | b64enc | quote }} 
  MOJSSO_ID: {{ .Values.secrets.MOJSSO_ID | b64enc | quote }} 
  MOJSSO_SECRET: {{ .Values.secrets.MOJSSO_SECRET | b64enc | quote }}
  RECAPTCHA_SECRET_KEY: {{ .Values.secrets.RECAPTCHA_SECRET_KEY | b64enc | quote }}
  RECAPTCHA_SITE_KEY: {{ .Values.secrets.RECAPTCHA_SITE_KEY | b64enc | quote }}
  SECRET_KEY_BASE: {{ .Values.secrets.SECRET_KEY_BASE | b64enc | quote }}
