apiVersion: v1
kind: Service
metadata:
  name: {{ template "nomis-api-access.fullname" . }}
  labels:
    app: {{ template "nomis-api-access.name" . }}
    chart: {{ template "nomis-api-access.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 80 
      targetPort: 3000 
      name: http
  selector:
    app: {{ template "nomis-api-access.name" . }}
    release: {{ .Release.Name }}
